
blank_issues_enabled: false
contact_links:
  - name: ✨ Feature Request / Idea / Q/A
    url: https://github.com/alibaba/formily/discussions/new
    about: Missing something in Formily? Let us know.
  - name: 📖 View documentation
    url: https://v2.formilyjs.org
    about: Official Formily documentation    
